name: "Call a Webhook when an issue is created"

on:
  issues:
    types:
      - opened
      - edited

jobs:
  send_webhook_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Webhook POST request
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://discord.com/api/webhooks/1219417054541648018/30_pZ5koZfFuRjjD0ibQ4sGK_6yF9B3rvkk68jyr-xa5y-8y5fLaZ9T9ZwN0pU_uf6U0"
          method: "POST"
          data: |
            {
              "username": "${{ github.event.sender.login }}",
              "avatar_url": "${{ github.event.sender.avatar_url }}",
              "content": "",
              "embeds": [
                {
                  "title": ${{ github.event.issue.title }},
                  "url": "${{ github.event.issue.url }}",
                  "description": ${{ github.event.issue.body }},
                  "color": 15258703,
                  "footer": {
                    "text": "Aren't Github Actions cool?",
                    "icon_url": "https://i.imgur.com/fKL31aD.jpg"
                  }
                }
              ]
            }
